import numpy as np
import matplotlib.pyplot as plt


def compute_intersection():
    """
    Solve t = 4(t - 30)
    """
    # t = 4t - 120
    # -3t = -120
    # t = 40
    t = 40
    E = t
    return t, E


def main():
    # Step 1: Time range
    t = np.linspace(0, 60, 1000)

    # Step 2: Energy equations
    E1 = t
    E2 = np.where(t < 30, 0, 4 * (t - 30))

    # Step 3: Solve intersection
    t_sol, E_sol = compute_intersection()

    # Step 4: Plot
    plt.figure()
    plt.title("Solar Panel Energy Comparison")
    plt.xlabel("Days since April 1")
    plt.ylabel("Energy (kilojoules)")

    # Step 5: Plot lines
    plt.plot(t, E1, label="Mach 1 (1 kJ/day)")
    plt.plot(t, E2, label="Mach 2 (4 kJ/day, starts at day 30)")

    # Step 6: Mark solution
    plt.axvline(x=t_sol, linestyle="--")
    plt.axhline(y=E_sol, linestyle="--")

    # Step 7: Finalize
    plt.legend()
    plt.xlim(0, 60)
    plt.ylim(0, 100)
    plt.show()

    # Step 8: Print results
    print(f"Equal energy occurs at day: {t_sol}")
    print(f"Energy generated by each: {E_sol} kJ")
    print(f"Total energy: {E_sol * 2} kJ")


if __name__ == "__main__":
    main()
